---
abstract: 'Handling inherited command-line options'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Getopt-Inherited
provides:
  Getopt::Inherited:
    file: lib/Getopt/Inherited.pm
    version: 1.100860
requires:
  Carp: 0
  Class::Accessor::Complex: 0
  Data::Inherited: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Getopt::Long: 0
  Pod::Usage: 0
  Scalar::Util: 0
  Test::More: 0.88
  constant: 0
  parent: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Getopt-Inherited
  homepage: http://search.cpan.org/dist/Getopt-Inherited/
  repository: http://github.com/hanekomu/Getopt-Inherited
version: 1.100860
